import json

# Mapped aliases for department codes with Reddit content
dept_alias_map = {
    "AAE": ["AAE", "AgEcon", "Ag Econ", "Agriculture and Applied Economics"],
    "ACCTIS": ["ACCTIS", "Accounting", "Acct", "ACCT I S"],
    "AFROAMER": ["AFROAMER", "Afro American", "African American"],
    "ANTHRO": ["ANTHRO", "Anthropology"],
    "ART": ["ART", "Art Dept", "Art"],
    "ASIALANG": ["ASIALANG", "AsianLang", "Asian Language", "Asian Lang"],
    "ASIAN": ["ASIAN", "Asian Studies"],
    "ASTRON": ["ASTRON", "Astronomy"],
    "BIOCHEM": ["BIOCHEM", "Biochem", "Biochemistry"],
    "BIOLOGY": ["BIOLOGY", "Bio", "Biology"],
    "CBE": ["CBE", "Chemical and Biological Engineering"],
    "CHEM": ["CHEM", "Chemistry"],
    "CHICLA": ["CHICLA", "Chican@", "Latinx Studies", "Latin@"],
    "COMARTS": ["COMARTS", "Comm Arts", "Communication Arts"],
    "COMPSCI": ["COMPSCI", "CS", "Computer Science", "Comp sci"],
    "COUNPSY": ["COUNPSY", "Counseling Psych"],
    "CSCS": ["CSCS", "Civil society and community studies"],
    "CURRIC": ["CURRIC", "Curriculum & Instruction"],
    "DANCE": ["DANCE", "Dance Dept"],
    "ECE": ["ECE", "Electrical Engineering", "CompE", "EE", "ECE UW"],
    "ECON": ["ECON", "Economics"],
    "EDPSYCH": ["EDPSYCH", "Educational Psychology", "Ed Psych"],
    "EMA": ["EMA", "Engineering Mechanics", "Aerospace"],
    "ENGL": ["ENGL", "English"],
    "ENTOM": ["ENTOM", "Entomology", "Bug Science"],
    "EPD": ["EPD", "Engineering Professional Development"],
    "ESL": ["ESL", "English as Second Language"],
    "FINANCE": ["FINANCE", "Finance Dept"],
    "FOLKLORE": ["FOLKLORE", "Myth Studies", "Folklore"],
    "GEN&WS": ["GEN&WS", "Gender Studies", "Women’s Studies"],
    "GENBUS": ["GENBUS", "General Business", "Gen Bus"],
    "GENETICS": ["GENETICS", "Genetics Dept"],
    "GEOG": ["GEOG", "Geography"],
    "GEOSCI": ["GEOSCI", "Geology", "Earth Science", "Geo Sci"],
    "GERMAN": ["GERMAN", "German Studies"],
    "HISTSCI": ["HISTSCI", "History of Science", "Hist Sci"],
    "ILS": ["ILS", "Integrated Liberal Studies", "I L S"],
    "INTER-LS": ["INTER-LS", "Inter-LS", "inter ls"],
    "INTEREGR": ["INTEREGR", "Inter EGR", "Inter Engineering"],
    "ISYE": ["ISYE", "ISyE", "Industrial Systems Engineering", "I S Ye", "I S Y E"],
    "JOURN": ["JOURN", "Journalism"],
    "KINES": ["KINES", "Kinesiology", "Exercise Science"],
    "LIS": ["LIS", "Library and Information Studies", "L I S"],
    "LITTRANS": ["LITTRANS", "Lit Trans", "Literature Translation"],
    "LSC": ["LSC", "Life Sciences Communication"],
    "MATH": ["MATH", "Mathematics", "maths"],
    "ME": ["ME", "Mechanical Engineering", "Mech E"],
    "MHR": ["MHR", "Management HR"],
    "MICROBIO": ["MICROBIO", "Microbiology", "Micro Bio"],
    "MM&I": ["MM&I", "Med Micro & Immunology"],
    "MS&E": ["MS&E", "Materials Science", "MSE"],
    "MUSIC": ["MUSIC", "Music Dept"],
    "NE": ["NE", "Nuclear Engineering"],
    "NUTRSCI": ["NUTRSCI", "Nutrition Science", "Nutr Sci"],
    "OBS&GYN": ["OBS&GYN", "ObGyn", "Obstetrics"],
    "OTM": ["OTM", "Operations & Tech Mgmt"],
    "PHILOS": ["PHILOS", "Philosophy"],
    "PHYSICS": ["PHYSICS", "Physics"],
    "PSYCH": ["PSYCH", "Psychology"],
    "RMI": ["RMI", "Risk Management"],
    "RP&SE": ["RP&SE", "Rehab Psych", "Special Ed"],
    "SCANDST": ["SCANDST", "Scandinavian Studies", "Sc and St"],
    "SOC": ["SOC", "Sociology"],
    "STAT": ["STAT", "Statistics", "Stats"],
    "THEATRE": ["THEATRE", "Theater", "Drama Dept"],
    "ZOOLOGY": ["ZOOLOGY", "Zoology", "Animal Biology"]
}

# Save to JSON file
with open("dept_alias_map.json", "w", encoding="utf-8") as f:
    json.dump(dept_alias_map, f, indent=2)

print("✅ Saved department alias map to 'dept_alias_map.json'")
